### PR TITLE
Gpt

### PR DESCRIPTION
**Pull request by lordotter**
GRUB-EFI ist ohne GPT Label nicht benutzbar

### CODE REVIEW

**Comment by Mrfai** [comment]
Please sent me your email address to fai @ fai-porject.rog since I like to sent you my comments on this pull request.

**Comment by mika** [comment]
@Mrfai JFYI, you can review and comment also directly within this PR (with the advantage that further people can read and possibly even contribute to the discussion).

**Comment by Mrfai** [comment]
Most changes seem to be special for your environment.
You are right, we do not have an example in disk_config for UEFI booting yet.

**Comment by CaptainSifff** [comment]
As a remark: I would be happy if I could leave out entirely the disklabel keyword in my disk_config 
and the disklabel would be chosen appropriately. msdos If booted from BIOS and GPT if booted from UEFI.

Currently I have modified 50-host-classes to scan the final string for occurences of my disk_config classes and the replace all occurences of e.g. DESKTOP with DESKTOP_UEFI. And I have a DESKTOP_UEFI disk_config class...

**Comment by Mrfai** [comment]
Closing since we now have UEFI examples.

@CaptainSifff: we cannot omit the disklabel in disk_config, because UEFI needs an additional partition with UEFI. So the disk_config for MBR or UEFI will be different. setup-storage should not change the partitioning scheme on its own.

**Pull request closed without merging**
