### PR TITLE
Protect (encrypted) root password: Do not provide it as argument

### PR DESCRIPTION
**Pull request by Flowdalic**
The encrypted root password was passed as argument to usermod. This
may enable other users to snoop the password by observing the running
processes. Especially if FAI softupdate runs are scheduled
periodically (e.g. on a daily basis). Even though the password appears
in its encrypted form, it should never appear in the list of running
processes.

Instead, use chpasswd with bash's "here strings" to protect the
encrypted root password. The chpasswd binary is part of shadow and
hence should be available everywhere.

This commit also unifies the place where the root password is potentially
set, while also enabling the "lock root account, and enabler sudo for
$username" if only the 'username' variable is set.

### CODE REVIEW

**Comment by Mrfai** [comment]
The patch looks good, but I will move your new script 01-set-root-password from class DEFAULT to FAIBASE. I also
adjust the shebang line to my  default usage /bin/bash

**Comment by Flowdalic** [comment]
> but I will move your new script 01-set-root-password from class DEFAULT to FAIBASE

Out of curiosity: Why?

**Comment by Mrfai** [comment]
The class DEFAULT is always defined by fai-class and should not be used in hooks and scripts. FAIBASE is defined by your config space and this can easily be changed. That's why I recommend not use DEFAULT.
And yes I use it in setup.DEFAULT.sh

**Comment by Mrfai** [comment]
Ooops, accidently closed.

**Comment by Mrfai** [comment]
I've added the chpasswd + here doc part of your patch. I do not like to change more in the CentOS example currently.
Thanks for you detailed commit message.

**Pull request closed without merging**
